version: "3.1"
services:
        #memcached:
        #image: memcached:alpine
        #container_name: laravel-app-memcached
        #networks:
        #- laravel-nginx-network

    redis:
      image: redis:alpine
      container_name: laravel-app-redis
      networks:
        - laravel-nginx-network

    postgres:
      image: postgres:9.6-alpine
            #image: postgres:9.5
      container_name: laravel-app-postgres
      working_dir: /var/lib/postgresql/data
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=nagatsu
      networks:
        - laravel-nginx-network

          #elasticsearch:
          #image: elasticsearch:5.4-alpine
          #container_name: app-elasticsearch
          #networks:
          #- code-network

    webserver:
      image: nginx:alpine
      container_name: laravel-webserver
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./var/log:/app/var/log
      ports:
       - "80:80"
         #links:
         #- php-fpm
      networks:
        - laravel-nginx-network

    php-fpm:
      build: docker/php-fpm
      container_name: laravel-php-fpm
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        - laravel-nginx-network

          #rabbitmq:
          #image: rabbitmq:3.7.4-management-alpine
          #volumes:
          #- ./data-rabbitmq:/var/lib/rabbitmq
          #ports:
          #- 5672:5672
          #- 15672:15672
          #environment:
          #- RABBITMQ_ERLANG_COOKIE=alabalaportocala
          #- RABBITMQ_DEFAULT_USER=root
          #- RABBITMQ_DEFAULT_PASS=1234
          #- RABBITMQ_DEFAULT_VHOST=/
          #networks:
          #- code-network

networks:
    laravel-nginx-network:
      driver: bridge
